BEGIN;

-- Split the MAL identity out of the overloaded `users` table into its own
-- `mal_profiles` table. After this migration `users` holds only native
-- accounts; every MAL identity is a 1:1 child of a native user and can be
-- attached/detached independently. The synced snapshot (user_anime_items)
-- stays keyed by users(id), so its ownership, primary key, indexes and RLS
-- policy are untouched.
CREATE TABLE mal_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mal_user_id BIGINT NOT NULL,
    mal_username TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 1:1 with users, and one MAL account maps to at most one profile globally.
CREATE UNIQUE INDEX mal_profiles_user_id_idx
    ON mal_profiles (user_id);

CREATE UNIQUE INDEX mal_profiles_mal_user_id_idx
    ON mal_profiles (mal_user_id);

-- Move every existing MAL identity into mal_profiles. The MAL username was
-- never stored separately before this split, so users.username is used as a
-- placeholder; it becomes accurate on the next OAuth link / sync.
INSERT INTO mal_profiles (user_id, mal_user_id, mal_username, created_at, updated_at)
SELECT id, mal_user_id, username, created_at, updated_at
FROM users
WHERE mal_user_id IS NOT NULL;

-- Re-key mal_tokens from users(id) to mal_profiles(id).
ALTER TABLE mal_tokens
    ADD COLUMN mal_profile_id INTEGER;

UPDATE mal_tokens t
SET mal_profile_id = p.id
FROM mal_profiles p
WHERE p.user_id = t.user_id;

-- Any token whose user has no MAL identity is meaningless after the split.
DELETE FROM mal_tokens WHERE mal_profile_id IS NULL;

-- Dropping user_id drops the old primary key and its foreign key.
ALTER TABLE mal_tokens DROP COLUMN user_id;

ALTER TABLE mal_tokens
    ALTER COLUMN mal_profile_id SET NOT NULL,
    ADD PRIMARY KEY (mal_profile_id),
    ADD CONSTRAINT mal_tokens_mal_profile_id_fkey
        FOREIGN KEY (mal_profile_id) REFERENCES mal_profiles(id) ON DELETE CASCADE;

-- Remove credential-less shell rows: public-sync snapshot containers
-- (no MAL id, no password). Their user_anime_items cascade away. MAL-only
-- login is removed, so these rows have no remaining purpose. (dev: data loss
-- here is acceptable.)
DELETE FROM users
WHERE password_hash IS NULL
  AND mal_user_id IS NULL;

-- The MAL identity now lives in mal_profiles.
DROP INDEX IF EXISTS users_mal_user_id_idx;

ALTER TABLE users
    DROP COLUMN mal_user_id;

COMMIT;
