BEGIN;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mal_user_id BIGINT,
    username TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX users_mal_user_id_idx
    ON users (mal_user_id);

CREATE UNIQUE INDEX users_username_lower_idx
    ON users (LOWER(username));

CREATE TABLE mal_tokens (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    access_token TEXT NOT NULL,
    refresh_token TEXT,
    token_type TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE anime_catalog (
    id INTEGER PRIMARY KEY,
    title TEXT,
    media_type TEXT,
    start_date DATE,
    img_small_url TEXT,
    img_large_url TEXT,
    num_episodes INTEGER NOT NULL DEFAULT 0 CHECK (num_episodes >= 0),
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    details_synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (id > 0)
);

CREATE INDEX catalog_resolved_idx
    ON anime_catalog (resolved, updated_at DESC);

CREATE TABLE anime_relations (
    id INTEGER NOT NULL REFERENCES anime_catalog(id) ON DELETE CASCADE,
    related_id INTEGER NOT NULL REFERENCES anime_catalog(id) ON DELETE CASCADE,
    relation_type TEXT,
    PRIMARY KEY (id, related_id),
    CHECK (id > 0),
    CHECK (related_id > 0),
    CHECK (id <> related_id)
);

CREATE INDEX anime_relations_related_idx
    ON anime_relations (related_id);

CREATE TABLE anime_franchises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_key TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX anime_franchises_member_key_idx
    ON anime_franchises (member_key);

CREATE TABLE anime_franchise_members (
    anime_id INTEGER PRIMARY KEY REFERENCES anime_catalog(id) ON DELETE CASCADE,
    franchise_id INTEGER NOT NULL REFERENCES anime_franchises(id) ON DELETE CASCADE,
    CHECK (anime_id > 0)
);

CREATE INDEX anime_franchise_members_franchise_idx
    ON anime_franchise_members (franchise_id, anime_id);

CREATE TABLE anime_list_statuses (
    id SMALLINT PRIMARY KEY,
    code TEXT NOT NULL,
    CHECK (id > 0),
    CHECK (code <> '')
);

CREATE UNIQUE INDEX anime_list_statuses_code_idx
    ON anime_list_statuses (code);

INSERT INTO anime_list_statuses (id, code)
VALUES
    (1, 'watching'),
    (2, 'completed'),
    (3, 'on_hold'),
    (4, 'dropped'),
    (5, 'plan_to_watch');

CREATE TABLE user_anime_items (
    user_id INTEGER NOT NULL DEFAULT NULLIF(current_setting('app.user_id', true), '')::INTEGER REFERENCES users(id) ON DELETE CASCADE,
    anime_id INTEGER NOT NULL REFERENCES anime_catalog(id) ON DELETE RESTRICT,
    list_status_id SMALLINT NOT NULL REFERENCES anime_list_statuses(id) ON DELETE RESTRICT,
    source_title TEXT NOT NULL,
    score INTEGER NOT NULL CHECK (score BETWEEN 0 AND 10),
    watched_episodes INTEGER NOT NULL CHECK (watched_episodes >= 0),
    synced_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, anime_id)
);

CREATE INDEX user_anime_items_user_idx
    ON user_anime_items (user_id);

CREATE INDEX user_anime_items_user_anime_idx
    ON user_anime_items (user_id, anime_id);

CREATE INDEX user_anime_items_user_status_idx
    ON user_anime_items (user_id, list_status_id);

ALTER TABLE user_anime_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_anime_items FORCE ROW LEVEL SECURITY;

CREATE POLICY user_anime_items_user_isolation ON user_anime_items
    USING (user_id = NULLIF(current_setting('app.user_id', true), '')::INTEGER)
    WITH CHECK (user_id = NULLIF(current_setting('app.user_id', true), '')::INTEGER);

COMMIT;
