BEGIN;

-- Restore the dead catalog timestamps and their index.
ALTER TABLE anime_catalog
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE anime_catalog
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX catalog_resolved_idx
    ON anime_catalog (resolved, updated_at DESC);

-- Snapshot the merged grouping so it can be rebuilt into the two-table shape.
-- member_key is the sorted member ids joined by ':', matching domain.BuildGroupKey.
CREATE TEMP TABLE franchise_groups ON COMMIT DROP AS
SELECT
    group_id,
    string_agg(anime_id::text, ':' ORDER BY anime_id) AS member_key
FROM anime_franchises
GROUP BY group_id;

CREATE TEMP TABLE franchise_member_map ON COMMIT DROP AS
SELECT anime_id, group_id
FROM anime_franchises;

DROP TABLE anime_franchises;

CREATE TABLE anime_franchises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_key TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX anime_franchises_member_key_idx
    ON anime_franchises (member_key);

CREATE TABLE anime_franchise_members (
    anime_id INTEGER PRIMARY KEY REFERENCES anime_catalog(id) ON DELETE CASCADE,
    franchise_id INTEGER NOT NULL REFERENCES anime_franchises(id) ON DELETE CASCADE,
    CHECK (anime_id > 0)
);

CREATE INDEX anime_franchise_members_franchise_idx
    ON anime_franchise_members (franchise_id, anime_id);

-- Recreate one franchise header per group, then re-key the members onto the new
-- surrogate ids by matching the reconstructed member_key.
WITH inserted AS (
    INSERT INTO anime_franchises (member_key)
    SELECT member_key FROM franchise_groups
    RETURNING id, member_key
)
INSERT INTO anime_franchise_members (anime_id, franchise_id)
SELECT fm.anime_id, ins.id
FROM franchise_member_map fm
JOIN franchise_groups fg ON fg.group_id = fm.group_id
JOIN inserted ins ON ins.member_key = fg.member_key;

COMMIT;
