CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mal_tokens (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    access_token TEXT NOT NULL,
    refresh_token TEXT,
    token_type TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS anime_entries (
    user_id INTEGER NOT NULL DEFAULT NULLIF(current_setting('app.user_id', true), '')::INTEGER REFERENCES users(id) ON DELETE CASCADE,
    anime_id INTEGER NOT NULL,
    anime_type TEXT NOT NULL CHECK (anime_type IN ('series', 'movie')),
    group_key TEXT NOT NULL,
    display_title TEXT NOT NULL,
    merged_titles INTEGER NOT NULL,
    avg_score DOUBLE PRECISION NOT NULL,
    watched_episodes_sum INTEGER NOT NULL,
    synced_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, anime_id)
);

CREATE INDEX IF NOT EXISTS anime_entries_user_type_idx
    ON anime_entries (user_id, anime_type);

CREATE INDEX IF NOT EXISTS anime_entries_user_group_key_idx
    ON anime_entries (user_id, group_key);

ALTER TABLE anime_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE anime_entries FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS anime_entries_user_isolation ON anime_entries;
CREATE POLICY anime_entries_user_isolation ON anime_entries
    USING (user_id = NULLIF(current_setting('app.user_id', true), '')::INTEGER)
    WITH CHECK (user_id = NULLIF(current_setting('app.user_id', true), '')::INTEGER);
