-- Authoritative reset/bootstrap schema for deploying the anikoro database
-- from zero. Apply this file to an empty database to create the full schema
-- in one step. It is not a migration file and must not be applied to a
-- database that already contains anikoro tables.
--
-- For an existing database, use the incremental migrations under
-- internal/adapters/postgres/migrations/ (run via `go run ./cmd/migrate up`).
-- This file and the migrations describe the same desired end state and must
-- be kept in sync whenever the schema changes.
--
-- Companion: drop_schema.sql is the local reset helper that drops everything
-- this file creates.

BEGIN;

-- Native accounts. The MAL identity lives in mal_profiles, attached 1:1.
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    -- Native account credentials. Populated for accounts registered with
    -- email + password.
    email TEXT,
    password_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX users_username_lower_idx
    ON users (LOWER(username));

-- Partial: email uniqueness applies only to rows that have an email.
CREATE UNIQUE INDEX users_email_lower_idx
    ON users (LOWER(email)) WHERE email IS NOT NULL;

-- MAL identity for a native user. 1:1 with users (UNIQUE user_id) and globally
-- unique per MAL account (UNIQUE mal_user_id). Created on OAuth link, deleted on
-- disconnect; cascades when the owning account is deleted.
CREATE TABLE mal_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mal_user_id BIGINT NOT NULL,
    mal_username TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX mal_profiles_user_id_idx
    ON mal_profiles (user_id);

CREATE UNIQUE INDEX mal_profiles_mal_user_id_idx
    ON mal_profiles (mal_user_id);

CREATE TABLE mal_tokens (
    mal_profile_id INTEGER PRIMARY KEY REFERENCES mal_profiles(id) ON DELETE CASCADE,
    access_token TEXT NOT NULL,
    refresh_token TEXT,
    token_type TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE anime_catalog (
    id INTEGER PRIMARY KEY,
    title TEXT,
    media_type TEXT,
    start_date DATE,
    -- MAL premiere season. Both columns stay NULL until details are hydrated
    -- from MAL; they are the authoritative season membership for the seasonal
    -- browse view (MAL assigns these directly rather than deriving them from
    -- start_date).
    start_season_year SMALLINT,
    start_season_name TEXT CHECK (
        start_season_name IS NULL
        OR start_season_name IN ('winter', 'spring', 'summer', 'fall')
    ),
    img_small_url TEXT,
    img_large_url TEXT,
    -- 0 means the episode count is unknown (not yet aired or missing on MAL).
    num_episodes INTEGER NOT NULL DEFAULT 0 CHECK (num_episodes >= 0),
    -- Community mean score from MAL (the `mean` field). NULL until MAL has a
    -- score; never 0. The "all anime" franchise rating is derived on read as
    -- AVG(mal_score) over the franchise members, so this is the only stored rating.
    mal_score NUMERIC(4, 2) CHECK (mal_score IS NULL OR (mal_score >= 0 AND mal_score <= 10)),
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    details_synced_at TIMESTAMPTZ,
    CHECK (id > 0)
);

CREATE INDEX catalog_start_season_idx
    ON anime_catalog (start_season_year, start_season_name);

CREATE INDEX catalog_mal_score_idx
    ON anime_catalog (mal_score DESC NULLS LAST);

-- Lazy-worker scan queues. The split sync model leaves new or incomplete catalog
-- entries as resolved=false stubs for the worker to hydrate (Pass A,
-- ListUnresolvedCatalogIDs), and the worker re-fetches resolved entries whose
-- details (and thus mal_score) have gone stale (Pass B, ListStaleCatalogIDs).
CREATE INDEX catalog_unresolved_idx
    ON anime_catalog (id) WHERE resolved = false;

CREATE INDEX catalog_stale_idx
    ON anime_catalog (details_synced_at NULLS FIRST, id) WHERE resolved = true;

CREATE TABLE anime_relations (
    id INTEGER NOT NULL REFERENCES anime_catalog(id) ON DELETE CASCADE,
    related_id INTEGER NOT NULL REFERENCES anime_catalog(id) ON DELETE CASCADE,
    relation_type TEXT,
    PRIMARY KEY (id, related_id),
    CHECK (id > 0),
    CHECK (related_id > 0),
    CHECK (id <> related_id)
);

CREATE INDEX anime_relations_related_idx
    ON anime_relations (related_id);

-- Anime grouped into franchises. Each row maps a catalog entry to the franchise
-- it belongs to, identified by group_id -- the smallest member id in the
-- connected component of the relation graph (excluding character/other links).
-- group_id is also the franchise's representative on read, so neither a separate
-- header row nor a MIN() lookup is needed. A standalone title is its own one-row
-- group (group_id = anime_id). The franchise refresh recomputes these rows from
-- anime_relations.
CREATE TABLE anime_franchises (
    anime_id INTEGER PRIMARY KEY REFERENCES anime_catalog(id) ON DELETE CASCADE,
    group_id INTEGER NOT NULL,
    CHECK (anime_id > 0),
    CHECK (group_id > 0),
    CHECK (group_id <= anime_id)
);

CREATE INDEX anime_franchises_group_idx
    ON anime_franchises (group_id, anime_id);

CREATE TABLE anime_list_statuses (
    id SMALLINT PRIMARY KEY,
    code TEXT NOT NULL,
    CHECK (id > 0),
    CHECK (code <> '')
);

CREATE UNIQUE INDEX anime_list_statuses_code_idx
    ON anime_list_statuses (code);

INSERT INTO anime_list_statuses (id, code)
VALUES
    (1, 'watching'),
    (2, 'completed'),
    (3, 'on_hold'),
    (4, 'dropped'),
    (5, 'plan_to_watch');

CREATE TABLE user_anime_items (
    user_id INTEGER NOT NULL DEFAULT NULLIF(current_setting('app.user_id', true), '')::INTEGER REFERENCES users(id) ON DELETE CASCADE,
    anime_id INTEGER NOT NULL REFERENCES anime_catalog(id) ON DELETE RESTRICT,
    list_status_id SMALLINT NOT NULL REFERENCES anime_list_statuses(id) ON DELETE RESTRICT,
    source_title TEXT NOT NULL,
    score INTEGER NOT NULL CHECK (score BETWEEN 0 AND 10),
    watched_episodes INTEGER NOT NULL CHECK (watched_episodes >= 0),
    synced_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, anime_id)
);

CREATE INDEX user_anime_items_user_idx
    ON user_anime_items (user_id);

CREATE INDEX user_anime_items_user_anime_idx
    ON user_anime_items (user_id, anime_id);

CREATE INDEX user_anime_items_user_status_idx
    ON user_anime_items (user_id, list_status_id);

ALTER TABLE user_anime_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_anime_items FORCE ROW LEVEL SECURITY;

CREATE POLICY user_anime_items_user_isolation ON user_anime_items
    USING (user_id = NULLIF(current_setting('app.user_id', true), '')::INTEGER)
    WITH CHECK (user_id = NULLIF(current_setting('app.user_id', true), '')::INTEGER);

COMMIT;
